<script src="{{ url('assets') }}/vendors/general/jquery/dist/jquery.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/popper.js/dist/umd/popper.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/js-cookie/src/js.cookie.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/moment/min/moment.min.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/sticky-js/dist/sticky.min.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/select2/dist/js/select2.full.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/ion-rangeslider/js/ion.rangeSlider.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/raphael/raphael.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/morris.js/morris.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/chart.js/dist/Chart.bundle.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/custom/js/vendors/sweetalert2.init.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/jquery.repeater/src/lib.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/jquery.repeater/src/jquery.input.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/jquery.repeater/src/repeater.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/vendors/general/dompurify/dist/purify.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/js/demo1/scripts.bundle.js" type="text/javascript"></script>
<script src="{{ url('assets') }}/js/demo1/pages/dashboard.js" type="text/javascript"></script>